spring:
  datasource:
    url: jdbc:postgresql://dpg-d86hkql7vvec73a82vpg-a:5432/portfolio_9rs6
    username: portfolio
    password: 9igAfFhfALfEyuNlgWRxA7zW4pXmnBT4
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false